language: cpp
compiler:
    - gcc

before_install:
    - mkdir deps
    - cd deps
    - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
    - sudo apt-get update -q
    - sudo apt-get install cmake
    - sudo apt-get install libsdl2
    - sudo apt-get install libsdl2-image
    - sudo apt-get install libbox2d2.3.0

    - mkdir build
    - cd build
    - cmake ..

script: make