dist: trusty
sudo: required
language: cpp
jdk:
  - oraclejdk8
matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
      env: COMPILER=clang++-3.8

addons:
  apt:
    packages:
      - p7zip-full
      - libbox2d-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libjansson-dev
      - python2.7
      - ant
      - git

before_install:
  - git clone https://github.com/facebook/buck.git /tmp/buck
  - cd /tmp/buck && ant && cd -
  - sudo ln -s /usr/bin/clang++-3.8 /usr/bin/clang++

script: /tmp/buck/bin/buck build :atena
