language: cpp
compiler:
    - gcc

before_install:
    - sudo apt-get update
    - sudo apt-get install cmake
    - sudo apt-get install libsdl2-2.0-0
    - sudo apt-get install libsdl2-image-2.0-0
    - sudo apt-get install libbox2d2.3.0

    - mkdir build
    - cd build
    - cmake ..

script: make